application: learndocfilmnoho
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static/css
  mime_type: text/css
  static_dir: static/css

- url: /.*
  script: main.app

libraries:
- name: django
  version: "latest"
